apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-todo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-todo
  template:
    metadata:
      labels:
        app: flask-todo
    spec:
      containers:
        - name: flask-todo-container
          image: komalbagwe31/flask-todo-app:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_HOST
              value: mongo
            - name: MONGO_PORT
              value: "27017"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-todo-service
spec:
  type: NodePort
  selector:
    app: flask-todo
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
