
services:
  web:
    build: .
    container_name: flask-todo-app
    ports:
      - "5001:5000"
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - FLASK_ENV=development
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
